### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by CurtisRose** [CurtisRose/hexGame#3]
Unit Movement
Units should be able to navigate the map.
Encapsulate the command in the command pattern.
Verify the move is valid (i.e. a friendly unit isn't already occupying a spot, or going to occupy the spot next turn)
If an enemy is on the tile the next turn, stop the unit short. (Attacking will handle the effect of this)

**Comment by krmoffett** [comment]
Not sure if I was doing anything wrong, but movement seems to be broken for me now. I place a unit, then select it and try to right-click to move, but every hex I tell him to move to shows as invalid. Then I push space and he disappears until I go to edit mode again.

**Comment by CurtisRose** [comment]
Okay, so space bar switches which team you are on, and, annoyingly, there are 8 teams, so you'd have to cycle back around.
Also, enter/return ends the turn.
And, the 'target' hex will be shown red (for now) that's probably a bad color I just randomly picked it. So it probably is a valid location, you just need to hit enter for him to do anything.

Obviously, I have to work on the UI/UX haha.

**Comment by CurtisRose** [comment]
This has been achieved.
